### ISSUE TITLE
IPA Replica mode

### ISSUE THREAD

**Issue by cevich** [yabhinav/ansible-role-ipaserver#7]
Installing a IPA replica would be a handy secondary-mode for this.  It would need access to much of the same data.  What's your feeling on this, could it be done here or would it make more sense as a separate role?  I'm willing to do the work/submit a PR.

**Comment by yabhinav** [comment]
thats certainly a handy feature we can incorporate...

**Comment by cevich** [comment]
Great, I've been working through a prototype, will open a PR when ready.
